images:
  directories:
    posts: images/posts
    gallery: images/gallery
    bookingMessages: images/messages
    serviceCategories: images/service-categories
    serviceSpecification: images/service-specification
    stylistBanners: images/banner
    stylistProfilePictures: images/profile-pictures
    userProfilePictures: images/user-profile-pictures
    reviewPictures: images/review-pictures
    providerProfilePictures: images/provider-profile-pictures
  defaultFormat: .webp
deleteAccountReasons:
  createdAccountByMistake: 
