
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      mapping:
        strategy: STANDARD
  main:
    web-application-type: servlet
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  # webflux:
  #   validator:
  #     enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}


app:
  app-name: Glamoor
  app-url: https://salonsynq.co.uk

  google-maps-api-key: ${GOOGLE_MAPS_API_KEY}
  get-address-io-api-key: GtbTElvGkUaiu1_7cWeNCg47297
  static-resources-path: /app/static-resources/
  images-base-url: https://s3.eu-west-2.amazonaws.com/salonsynq-app-images/
  images:
    directories:
      posts: images/posts
      gallery: images/gallery
      booking-messages: images/messages
      service-categories: images/service-categories
      service-specification: images/service-specification
      salon-banners: images/banner
      salon-profile-pictures: images/profile-pictures
      user-profile-pictures: images/user-profile-pictures
      review-pictures: images/review-pictures
      provider-profile-pictures: images/provider-profile-pictures
    default-format: .webp
  delete-account-reasons:
    created-account-by-mistake: "I created this account by mistake"
    do-not-want-to-use-app-anymore: "I do not want to use ${app.app-name} App anymore"
    cannot-find-salons: "I can not find salons that I like"
    other: "Other"
  support-email-address: hello@glamoor.com
  future-booking-days-extent: 150
  show-post-like-count: false
  query-results-max-distance: 100000
  default-longitude: -0.2664051
  default-latitude: 51.5287398
  time-slot-reservation-duration-seconds: 600
  time-slot-heartbeat-cadence-seconds: 60


api:
  customers-api:
    base-url: ${CUSTOMERS_API_BASE_URL}
    request-timeout: ${API_REQUEST_TIMEOUT}
  salons-api:
    base-url: ${SALONS_API_BASE_URL}
    request-timeout: ${API_REQUEST_TIMEOUT}
  payments-api:
    base-url: ${PAYMENTS_API_BASE_URL}
    request-timeout: ${API_REQUEST_TIMEOUT}
  bookings-api:
    base-url: ${BOOKINGS_API_BASE_URL}
    request-timeout: ${API_REQUEST_TIMEOUT}
  gateway-api:
    base-url: ${GATEWAY_API_BASE_URL}
    request-timeout: ${API_REQUEST_TIMEOUT}

