

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddResponseHeader=X-Content-Type-Options, nosniff
        - AddResponseHeader=X-XSS-Protection, 1; mode=block
        - AddResponseHeader=Content-Security-Policy, "default-src 'self'"
      
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


server:
  port: 80


client:
  android:
    - version: 1.0.0
      settings-version: 7
      latest-version: 1.0.0
      mandatory-update: false
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
  ios:
    - version: 1.0.0
      settings-version: 10
      latest-version: 1.0.0
      mandatory-update: false
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
  web:
    - version: 1.0.0
      settings-version: 7
      latest-version: 1.0.0
      mandatory-update: false
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
