

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddResponseHeader=X-Content-Type-Options, nosniff
        - AddResponseHeader=X-XSS-Protection, 1; mode=block
        - AddResponseHeader=Content-Security-Policy, "default-src 'self'"
      
  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8000


client:
  android:
    - version: 1.0.0
      settings-version: 7
      latest-version: 1.0.0
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
      mandatory-update: false
  ios:
    - version: 1.0.0
      settings-version: 7
      latest-version: 1.0.0
      default-map-zoom: 14.4746
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
      mandatory-update: false
  web:
    - version: 1.0.0
      settings-version: 7
      latest-version: 1.0.0
      sign-in-options:
        google: true
        facebook: false
        apple: false
        email-and-password: true
      default-map-zoom: 14.4746
      mandatory-update: false
