
spring:
  application:
    name: salons
      
      
server:
  port: 8008


salons-app:
  salons-request-batch-size-for-home-view: 14
  salons-request-batch-size: 20
  service-specification-request-batch-size: 30
  service-specification-request-batch-size-mini: 5
  service-request-batch-size: 20
  service-category-request-batch-size: 20
  addon-request-batch-size: 20
